version: 2.1

orbs:
  codecov: codecov/codecov@3 # Use version 3 or 4 (5 is still very new and might have issues)

jobs:
  test:
    docker:
      - image: cimg/node:20.10 # Adjust Node.js version if needed
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests with coverage
          command: npx vitest run --coverage
      - run:
          name: Upload coverage to Coveralls
          command: cat ./coverage/lcov.info | npx coveralls --repo-token $COVERALLS_REPO_TOKEN
      - codecov/upload:
          file: ./coverage/lcov.info # Upload to Codecov

workflows:
  test_and_upload_coverage:
    jobs:
      - test
 