version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.10 # Adjust the Node.js version if needed
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests with coverage
          command: npx vitest run --coverage
      - run:
          name: Upload coverage to Coveralls
          command: cat ./coverage/lcov.info | npx coveralls --repo-token $COVERALLS_REPO_TOKEN
      - run:
          name: Upload coverage to Codecov
          command: npx codecov -f coverage/lcov.info

workflows:
  version: 2
  test_pipeline:
    jobs:
      - test
orbs:
  codecov: codecov/codecov@5
workflows:
  upload-to-codecov:
    jobs:
      - checkout 
      - codecov/upload